#!/Users/fielding/.rbenv/versions/1.9.2-p290/bin/ruby
# FieldMatter - git post-receive hook

require '/Users/fielding/work/fieldMatter/lib/fieldMatter.rb'

dm = FieldMatter::DarkMatter.new('/Users/fielding/notes')
dm.update

## might add update_repo( repo ) for DarkMatter that combines the above in to one line