#!/usr/bin/env ruby
# FieldMatter - git post-receive hook

$LOAD_PATH.unshift(File.dirname(__FILE__) + '/../lib') unless $LOAD_PATH.include?(File.dirname(__FILE__) + '/../lib')

require 'fieldmatter'

# TODO: add configuration for repo directory 
dm = FieldMatter::DarkMatter.new('/Users/fielding/notes')
dm.update